[[rtmidi]]
arch = "aarch64"
git-tree-sha1 = "58999c04a8b2ca3b216340d33bb5ecc920c05677"
os = "macos"

    [[rtmidi.download]]
    sha256 = "047377f97491f4b3eb896a40e8ae4d16b5d2531cbd525e0222c13a5a299527c3"
    url = "https://github.com/JuliaBinaryWrappers/rtmidi_jll.jl/releases/download/rtmidi-v6.0.0+0/rtmidi.v6.0.0.aarch64-apple-darwin.tar.gz"
[[rtmidi]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f6a94485346ca96929ea86934b388b57eef71e8a"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "f68cf837416a523b2912afea949363d27a02963280b793e2d9a69d3a1c3dffcf"
    url = "https://github.com/JuliaBinaryWrappers/rtmidi_jll.jl/releases/download/rtmidi-v6.0.0+0/rtmidi.v6.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[rtmidi]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "24caa088e8cf03fb34b70fffb49277d183e21668"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "b8f72cd7d8dc86ea29bdbd322aec722f163ff9c785aba410c7ea678fe5c06316"
    url = "https://github.com/JuliaBinaryWrappers/rtmidi_jll.jl/releases/download/rtmidi-v6.0.0+0/rtmidi.v6.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[rtmidi]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8e00fff1fe7395fcda4b424ffb5d96ae57edc913"
libc = "musl"
os = "linux"

    [[rtmidi.download]]
    sha256 = "ee6f8f3d86d3c1aa1bb82a3d3d6d6b0917391672c299ca301a1142755f94c546"
    url = "https://github.com/JuliaBinaryWrappers/rtmidi_jll.jl/releases/download/rtmidi-v6.0.0+0/rtmidi.v6.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[rtmidi]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5252e4931bc68725f2834c98173ce0a36d76e2c3"
libc = "musl"
os = "linux"

    [[rtmidi.download]]
    sha256 = "9673df1184079fcf26b324423d87db995d4a2097ccc5537dfd0d075610706204"
    url = "https://github.com/JuliaBinaryWrappers/rtmidi_jll.jl/releases/download/rtmidi-v6.0.0+0/rtmidi.v6.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[rtmidi]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "94f39c88b7d32aff4be13e33a7991c4a937458fd"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "ba56377ace2861066179b3871684ad187753ceec9f8a9fc4931f03fa0ae5db36"
    url = "https://github.com/JuliaBinaryWrappers/rtmidi_jll.jl/releases/download/rtmidi-v6.0.0+0/rtmidi.v6.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[rtmidi]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f57234bae8db7ac03555ebea2620e9b7f9df65e9"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "04bc49e13428d3d051a3a55b943dd551aa7b791677c5bc76a3f74f4e05fe61ee"
    url = "https://github.com/JuliaBinaryWrappers/rtmidi_jll.jl/releases/download/rtmidi-v6.0.0+0/rtmidi.v6.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[rtmidi]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "36ceefc2213fef626636bc40c90d955e96831469"
libc = "musl"
os = "linux"

    [[rtmidi.download]]
    sha256 = "c4b8076b0f322595e5eb86a93161ef4f81fc850ac321d565826c6726caa59b7c"
    url = "https://github.com/JuliaBinaryWrappers/rtmidi_jll.jl/releases/download/rtmidi-v6.0.0+0/rtmidi.v6.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[rtmidi]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8869ece3fca383050fb3514588bc90ec33f8f2bd"
libc = "musl"
os = "linux"

    [[rtmidi.download]]
    sha256 = "a15bf9b567f9ada74a2af4b07990a01e6023bfd1cb5cc9a806d7335e4092b927"
    url = "https://github.com/JuliaBinaryWrappers/rtmidi_jll.jl/releases/download/rtmidi-v6.0.0+0/rtmidi.v6.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[rtmidi]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f4d7b6c22d292df6c23d7c323b9bbcc6c20ec297"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "ffb3f583b5d70dc08a07399482eb2e0da6222454dccff5746f4b7df8a6c3399b"
    url = "https://github.com/JuliaBinaryWrappers/rtmidi_jll.jl/releases/download/rtmidi-v6.0.0+0/rtmidi.v6.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[rtmidi]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c796d07bf21f58b58f92bfdbf3ab5db2f4fb44a3"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "76ff8a4e6f168da4b796e74c72216769532e08f71fcd6b10d68cafc1c8bc3714"
    url = "https://github.com/JuliaBinaryWrappers/rtmidi_jll.jl/releases/download/rtmidi-v6.0.0+0/rtmidi.v6.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[rtmidi]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d3b5fcd38ae15941dfa2c62b75d0e5f0c908df73"
libc = "musl"
os = "linux"

    [[rtmidi.download]]
    sha256 = "440786eb467efdaadeb8760d72bab127279aad6a3239789a580d356d59dae2e3"
    url = "https://github.com/JuliaBinaryWrappers/rtmidi_jll.jl/releases/download/rtmidi-v6.0.0+0/rtmidi.v6.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[rtmidi]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "86f81488bd2c9f2f8c01ffcc8a550371f256e5a3"
libc = "musl"
os = "linux"

    [[rtmidi.download]]
    sha256 = "6dcc9975367013f94eebe5aa3174ed62d366a667f03429e33ef0f14499209fd7"
    url = "https://github.com/JuliaBinaryWrappers/rtmidi_jll.jl/releases/download/rtmidi-v6.0.0+0/rtmidi.v6.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[rtmidi]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2ad86c9c43c9a3a3bc7e8f6c0a085ca9b1be75bb"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "d3f6057f8357ac3603067696f7eda73e40336a293553a50d12d66611dc6ccc55"
    url = "https://github.com/JuliaBinaryWrappers/rtmidi_jll.jl/releases/download/rtmidi-v6.0.0+0/rtmidi.v6.0.0.i686-linux-gnu-cxx03.tar.gz"
[[rtmidi]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a73ebe3fd82038d801bd193368e1156b5ed7c881"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "7a43ba3df74bfe9fc77a21910a48ee7646e9ce993f07446b6264014ebc9798bc"
    url = "https://github.com/JuliaBinaryWrappers/rtmidi_jll.jl/releases/download/rtmidi-v6.0.0+0/rtmidi.v6.0.0.i686-linux-gnu-cxx11.tar.gz"
[[rtmidi]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c2519b524cb914c37504e5064c45a3d9ebd293b1"
libc = "musl"
os = "linux"

    [[rtmidi.download]]
    sha256 = "437df33e81539a9810d4b3d956254dbc6145ac28bf6a417f926240edc213fd37"
    url = "https://github.com/JuliaBinaryWrappers/rtmidi_jll.jl/releases/download/rtmidi-v6.0.0+0/rtmidi.v6.0.0.i686-linux-musl-cxx03.tar.gz"
[[rtmidi]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "faf5f7067c63531c856337e107f05c8043325665"
libc = "musl"
os = "linux"

    [[rtmidi.download]]
    sha256 = "651f32bef81790260c23d52f92c85f20a62e02606294a86ec6086066e9e1800a"
    url = "https://github.com/JuliaBinaryWrappers/rtmidi_jll.jl/releases/download/rtmidi-v6.0.0+0/rtmidi.v6.0.0.i686-linux-musl-cxx11.tar.gz"
[[rtmidi]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3e222e304295a6ea32c7f6bbe56bc3e5d86986de"
os = "windows"

    [[rtmidi.download]]
    sha256 = "1ccc54131e5d2eb6eaaead98e0146b6218a4ce976085d30f7ae27bcd36c22680"
    url = "https://github.com/JuliaBinaryWrappers/rtmidi_jll.jl/releases/download/rtmidi-v6.0.0+0/rtmidi.v6.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[rtmidi]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e8b81c7e772b0d051e40cc3d6f36466f2463efa6"
os = "windows"

    [[rtmidi.download]]
    sha256 = "e9f1339a95c353052aa6711a15a61ac958d29fe9bebbb1a3cff681891a92efbd"
    url = "https://github.com/JuliaBinaryWrappers/rtmidi_jll.jl/releases/download/rtmidi-v6.0.0+0/rtmidi.v6.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[rtmidi]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cbc4b24ef056f38343dd4c470768565668a2510a"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "a780a790fea1c24c32348e56fe901a44b1e83062f28181563b2b7a929c31827d"
    url = "https://github.com/JuliaBinaryWrappers/rtmidi_jll.jl/releases/download/rtmidi-v6.0.0+0/rtmidi.v6.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[rtmidi]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4911a0f3d173545c0019f20e0f5b6ed2f08f6891"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "1e36f073b4adff8f5d5159c4570a43e7da24dab86b90af0444f11c15e3f7c0f1"
    url = "https://github.com/JuliaBinaryWrappers/rtmidi_jll.jl/releases/download/rtmidi-v6.0.0+0/rtmidi.v6.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[rtmidi]]
arch = "x86_64"
git-tree-sha1 = "8b6fd7aca9a6c31b883e156e302f4fdf215c7c34"
os = "macos"

    [[rtmidi.download]]
    sha256 = "b9ffb141683ff6bddc88aee74d11f05c593a2170c1315fa91d186df87f568205"
    url = "https://github.com/JuliaBinaryWrappers/rtmidi_jll.jl/releases/download/rtmidi-v6.0.0+0/rtmidi.v6.0.0.x86_64-apple-darwin.tar.gz"
[[rtmidi]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b90c8d1e4fc0b6032a8b29f8a3121a35b7362a01"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "f36adf901682d44b8367de1bdb0af102edf798ef21795bd5e48b6d7b65761a07"
    url = "https://github.com/JuliaBinaryWrappers/rtmidi_jll.jl/releases/download/rtmidi-v6.0.0+0/rtmidi.v6.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[rtmidi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ffc0026a476ec6576763512f2cba1d446507b76c"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "c203bc17bace02af8a5aba29ffdf0859fb36568ac4a08dbdcc98deb5b3ec13c5"
    url = "https://github.com/JuliaBinaryWrappers/rtmidi_jll.jl/releases/download/rtmidi-v6.0.0+0/rtmidi.v6.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[rtmidi]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c8fe0be85a59516aae463955a05329255ebd865b"
libc = "musl"
os = "linux"

    [[rtmidi.download]]
    sha256 = "562104455d007e39ce1b73d19160144db26af949da19da6624db4e8a533aec0d"
    url = "https://github.com/JuliaBinaryWrappers/rtmidi_jll.jl/releases/download/rtmidi-v6.0.0+0/rtmidi.v6.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[rtmidi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e310da4103f7be597f1f2358ace6063dbabc36f1"
libc = "musl"
os = "linux"

    [[rtmidi.download]]
    sha256 = "a425b3c766b86780d4c91b4f6e9d65fc0dba286d5299e239f8639c915ed9abfa"
    url = "https://github.com/JuliaBinaryWrappers/rtmidi_jll.jl/releases/download/rtmidi-v6.0.0+0/rtmidi.v6.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[rtmidi]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "20e90227b745ad1fc54d78496aa39da3f70a376b"
os = "windows"

    [[rtmidi.download]]
    sha256 = "55644ec6777af51e38404b987cc13b58182756cde1a21771663d9b5e414c3310"
    url = "https://github.com/JuliaBinaryWrappers/rtmidi_jll.jl/releases/download/rtmidi-v6.0.0+0/rtmidi.v6.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[rtmidi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "41c8a6cf3e235e26eaa0c2b530d5ca88165b2b71"
os = "windows"

    [[rtmidi.download]]
    sha256 = "feea70cf57300cebc25044a9662877bbd3ad0e93985a067a3bce002f96b4ed0b"
    url = "https://github.com/JuliaBinaryWrappers/rtmidi_jll.jl/releases/download/rtmidi-v6.0.0+0/rtmidi.v6.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
